In [134]:
import pandas as pd
import osmnx as ox
import folium
import geopandas as gpd
from shapely.geometry import Point
from datetime import datetime
import networkx as nx

In [3]:
df_risk = pd.read_csv('../data/NYC_risk.csv', index_col=0)
geometry = [Point(xy) for xy in zip(df_risk.longitude, df_risk.latitude)]
gdf_risk = gpd.GeoDataFrame(df_risk, crs="EPSG:4326", geometry=geometry)

In [4]:
gdf_risk.head()

latitude  longitude  accidents  total_injured  total_killed  \
0  40.501465 -74.245230          1            0.0           0.0   
1  40.503310 -74.237465          1            0.0           0.0   
2  40.503387 -74.248830          1            0.0           0.0   
3  40.503414 -74.244960          1            0.0           0.0   
4  40.504470 -74.243454          1            0.0           0.0   

                     geometry  
0  POINT (-74.24523 40.50147)  
1  POINT (-74.23747 40.50331)  
2  POINT (-74.24883 40.50339)  
3  POINT (-74.24496 40.50341)  
4  POINT (-74.24345 40.50447)

In [5]:
G = ox.load_graphml(filepath='../data/NYC_drive.osm')

In [6]:
nodes_proj, edges_proj = ox.graph_to_gdfs(G, nodes=True, edges=True)

In [37]:
edges_proj.head()

osmid  oneway  \
u        v         key                                            
39076461 42854803  0                           25161578    True   
         274283981 0              [122633397, 25161349]    True   
39076490 277672046 0                            5699971    True   
         277672005 0                           39084898    True   
39076504 462124701 0    [618709517, 618709515, 5700693]    True   

                              highway   length  \
u        v         key                           
39076461 42854803  0    motorway_link  254.709   
         274283981 0         motorway  767.800   
39076490 277672046 0    motorway_link  259.674   
         277672005 0         motorway  291.839   
39076504 462124701 0    motorway_link  433.148   

                                                                 geometry  \
u        v         key                                                      
39076461 42854803  0    LINESTRING (-73.79463 40.78641, -73.79361 40.7...   
         274283981 0    LINESTRING (-73.79463 40.78641, -73.79309 40.7...   
39076490 277672046 0    LINESTRING (-73.75709 40.76243, -73.75721 40.7...   
         277672005 0    LINESTRING (-73.75709 40.76243, -73.75741 40.7...   
39076504 462124701 0    LINESTRING (-73.74416 40.75347, -73.74453 40.7...   

                       lanes  ref                  name maxspeed bridge  \
u        v         key                                                    
39076461 42854803  0     NaN  NaN                   NaN      NaN    NaN   
         274283981 0       2  CIP  Cross Island Parkway   50 mph    NaN   
39076490 277672046 0     NaN  NaN                   NaN      NaN    NaN   
         277672005 0       3  CIP  Cross Island Parkway   50 mph    NaN   
39076504 462124701 0       1  NaN                   NaN      NaN    yes   

                       access tunnel width junction service  
u        v         key                                       
39076461 42854803  0      NaN    NaN   NaN      NaN     NaN  
         274283981 0      NaN    NaN   NaN      NaN     NaN  
39076490 277672046 0      NaN    NaN   NaN      NaN     NaN  
         277672005 0      NaN    NaN   NaN      NaN     NaN  
39076504 462124701 0      NaN    NaN   NaN      NaN     NaN

In [54]:
gdf_problem = gdf_risk.iloc[[3,
5,
10,
12,
17,
19,
21,
22,
25,
26,
28,
32,
33,
35,
38,
39,
40,
41,
43,
49,
53,
59,
60,
62,
64,
65,
68,
69,
71,
72,
75,
76,
78,
79,
81,
83,
85,
87,
89,
91,
92],:]
gdf_problem

latitude  longitude  accidents  total_injured  total_killed  \
3   40.503414 -74.244960          1            0.0           0.0   
5   40.504482 -74.247270          1            2.0           0.0   
10  40.507458 -74.235855          1            0.0           0.0   
12  40.507880 -74.229240          1            0.0           0.0   
17  40.509180 -74.247040          1            0.0           0.0   
19  40.509666 -74.218070          1            2.0           0.0   
21  40.510080 -74.250760          1            0.0           0.0   
22  40.510117 -74.249200          1            0.0           0.0   
25  40.511127 -74.248886          1            0.0           0.0   
26  40.511147 -74.241290          1            0.0           0.0   
28  40.511670 -74.249410          1            0.0           0.0   
32  40.512028 -74.249760          3            0.0           0.0   
33  40.512060 -74.250824          1            0.0           0.0   
35  40.512470 -74.236984          1            0.0           0.0   
38  40.513320 -74.244390          1            0.0           0.0   
39  40.513325 -74.248085          1            0.0           0.0   
40  40.513470 -74.248890          1            0.0           0.0   
41  40.513480 -74.247760          1            0.0           0.0   
43  40.514103 -74.243256          1            0.0           0.0   
49  40.514534 -74.211520          1            2.0           0.0   
53  40.514957 -74.245390          1            0.0           0.0   
59  40.516457 -74.196884          1            0.0           0.0   
60  40.516594 -74.237660          1            0.0           0.0   
62  40.516804 -74.233480          1            2.0           0.0   
64  40.516956 -74.233690          1            0.0           0.0   
65  40.517100 -74.233894          7            0.0           0.0   
68  40.518000 -74.212620          1            0.0           0.0   
69  40.518196 -74.223800          2            2.0           0.0   
71  40.518520 -74.197080          1            0.0           0.0   
72  40.519054 -74.229800          1            0.0           0.0   
75  40.520092 -74.188160          1            0.0           0.0   
76  40.520283 -74.196470          1            0.0           0.0   
78  40.521038 -74.236565          1            0.0           0.0   
79  40.521140 -74.217240          3            0.0           0.0   
81  40.521835 -74.235040          1            0.0           0.0   
83  40.521935 -74.216900          1            0.0           0.0   
85  40.522522 -74.209660          1            0.0           0.0   
87  40.522808 -74.234924          1            2.0           0.0   
89  40.523464 -74.234856          1            0.0           0.0   
91  40.523624 -74.199554          1            0.0           0.0   
92  40.523884 -74.239204          1            2.0           0.0   

                      geometry  
3   POINT (-74.24496 40.50341)  
5   POINT (-74.24727 40.50448)  
10  POINT (-74.23586 40.50746)  
12  POINT (-74.22924 40.50788)  
17  POINT (-74.24704 40.50918)  
19  POINT (-74.21807 40.50967)  
21  POINT (-74.25076 40.51008)  
22  POINT (-74.24920 40.51012)  
25  POINT (-74.24889 40.51113)  
26  POINT (-74.24129 40.51115)  
28  POINT (-74.24941 40.51167)  
32  POINT (-74.24976 40.51203)  
33  POINT (-74.25082 40.51206)  
35  POINT (-74.23698 40.51247)  
38  POINT (-74.24439 40.51332)  
39  POINT (-74.24809 40.51333)  
40  POINT (-74.24889 40.51347)  
41  POINT (-74.24776 40.51348)  
43  POINT (-74.24326 40.51410)  
49  POINT (-74.21152 40.51453)  
53  POINT (-74.24539 40.51496)  
59  POINT (-74.19688 40.51646)  
60  POINT (-74.23766 40.51659)  
62  POINT (-74.23348 40.51680)  
64  POINT (-74.23369 40.51696)  
65  POINT (-74.23389 40.51710)  
68  POINT (-74.21262 40.51800)  
69  POINT (-74.22380 40.51820)  
71  POINT (-74.19708 40.51852)  
72  POINT (-74.22980 40.51905)  
75  POINT (-74.18816 40.52009)  
76  POINT (-74.19647 40.52028)  
78  POINT (-74.23656 40.52104)  
79  POINT (-74.21724 40.52

In [156]:
gdf_problem.accidents.sum()

52

In [159]:
gdf_problem.shape

(41, 6)

In [158]:
df_risk = pd.read_csv('../data/NYC_risk.csv', index_col=0)
df_risk = df_risk.loc[0:99]
df_risk.accidents.sum()

134

In [31]:
gdf_joined =  gpd.sjoin(edges_proj, gdf_risk, how='left', op='intersects', lsuffix='left', rsuffix='right')

In [32]:
gdf_joined.shape

(140811, 21)

In [33]:
gdf_joined.isna().sum()

osmid                 0
oneway                0
highway               0
length                0
geometry              0
lanes            124243
ref              137717
name               3876
maxspeed         126803
bridge           138730
access           140309
tunnel           140605
width            140776
junction         140662
service          140808
index_right      140750
latitude         140750
longitude        140750
accidents        140750
total_injured    140750
total_killed     140750
dtype: int64

In [43]:
from scipy.spatial import cKDTree
from shapely.geometry import Point
import numpy as np

import itertools
from operator import itemgetter

In [44]:
def ckdnearest(gdfA, gdfB, gdfB_cols=['osmid']):
    A = np.concatenate(
        [np.array(geom.coords) for geom in gdfA.geometry.to_list()])
    B = [np.array(geom.coords) for geom in gdfB.geometry.to_list()]
    B_ix = tuple(itertools.chain.from_iterable(
        [itertools.repeat(i, x) for i, x in enumerate(list(map(len, B)))]))
    B = np.concatenate(B)
    ckd_tree = cKDTree(B)
    dist, idx = ckd_tree.query(A, k=1)
    idx = itemgetter(*idx)(B_ix)
    gdf = pd.concat(
        [gdfA, gdfB.loc[idx, gdfB_cols].reset_index(drop=True),
         pd.Series(dist, name='dist')], axis=1)
    return gdf


In [45]:
ckdnearest(gdf_problem, edges_proj)

KeyError: (107059, 107064, 97661)

In [55]:
gdf_problem["gdf2_idx"] = gdf_problem.apply(
    lambda row1: edges_proj.apply(
        lambda row2: row1.geometry.distance(row2.geometry), axis="columns").idxmin(),
    axis="columns"
)

KeyboardInterrupt: 

In [ ]:
gdf_problem.head()

In [ ]:
latitude = 40.677834
longitude = -74.012443
map_nyc = folium.Map(location=[latitude, longitude], zoom_start=10)
    
for idx, row in gdf_problem.iterrows():
    folium.Marker((row.latitude, row.longitude), icon=folium.Icon(color="green")).add_to(map_nyc)
    folium.Choropleth(edges_proj.loc[row.gdf2_idx, "geometry"], popup=idx, line_weight=5, line_color='red', line_opacity=0.5).add_to(map_nyc)

map_nyc

## Trouvé sur le github de geopandas

In [56]:
import geopandas as gpd
import osmnx as ox
from shapely.geometry import LineString

def sjoin_nearest(left_df, right_df, op='intersects', search_dist=0.03, report_dist=False,
                  lsuffix='left', rsuffix='right'):
    """
    Perform a spatial join between two input layers.
    If a geometry in left_df falls outside (all) geometries in right_df, the data from nearest Polygon will be used as a result.
    To make queries faster, "search_dist" -parameter (specified in map units) can be used to limit the search area for geometries around source points.
    If report_dist == True, the distance for closest geometry will be reported in a column called `dist`. If geometries intersect, the distance will be 0.

    """

    # Explode possible MultiGeometries
    right_df = right_df.explode()
    right_df = right_df.reset_index(drop=True)

    if 'index_left' in left_df.columns:
        left_df = left_df.drop('index_left', axis=1)

    if 'index_right' in left_df.columns:
        left_df = left_df.drop('index_right', axis=1)

    if report_dist:
        if 'dist' in left_df.columns:
            raise ValueError("'dist' column exists in the left DataFrame. Remove it, or set 'report_dist' to False.")

    # Get geometries that intersect or do not intersect polygons
    mask = left_df.intersects(right_df.unary_union)
    geoms_intersecting_polygons = left_df.loc[mask]
    geoms_outside_polygons = left_df.loc[~mask]

    # Make spatial join between points that fall inside the Polygons
    if geoms_intersecting_polygons.shape[0] > 0:
        pip_join = gpd.sjoin(left_df=geoms_intersecting_polygons, right_df=right_df, op=op)

        if report_dist:
            pip_join['dist'] = 0

    else:
        pip_join = gpd.GeoDataFrame()

    # Get nearest geometries
    closest_geometries = gpd.GeoDataFrame()

    # A tiny snap distance buffer is needed in some cases
    snap_dist = 0.00000005

    # Closest points from source-points to polygons
    for idx, geom in geoms_outside_polygons.iterrows():
        # Get geometries within search distance
        candidates = right_df.loc[right_df.intersects(geom[left_df.geometry.name].buffer(search_dist))]

        if len(candidates) == 0:
            continue
        unary = candidates.unary_union

        if unary.geom_type == 'Polygon':

            # Get exterior of the Polygon
            exterior = unary.exterior

            # Find a point from Polygons that is closest to the source point
            closest_geom = exterior.interpolate(exterior.project(geom[left_df.geometry.name]))

            if report_dist:
                distance = closest_geom.distance(geom[left_df.geometry.name])

            # Select the Polygon
            closest_poly = right_df.loc[right_df.intersects(closest_geom.buffer(snap_dist))]

        elif unary.geom_type == 'MultiPolygon':
            # Keep track of distance for closest polygon
            distance = 9999999999
            closest_geom = None

            for idx, poly in enumerate(unary):
                # Get exterior of the Polygon
                exterior = poly.exterior

                # Find a point from Polygons that is closest to the source point
                closest_candidate = exterior.interpolate(exterior.project(geom[left_df.geometry.name]))

                # Calculate distance between origin point and the closest point in Polygon
                dist = geom[left_df.geometry.name].distance(closest_candidate)

                # If the point is closer to given polygon update the info
                if dist < distance:
                    distance = dist
                    closest_geom = closest_candidate

            # Select the Polygon that was closest
            closest_poly = right_df.loc[right_df.intersects(closest_geom.buffer(snap_dist))]
        else:
            print("Incorrect input geometry type. Skipping ..")

        # Reset index
        geom = geom.to_frame().T.reset_index(drop=True)

        # Drop geometry from closest polygon
        closest_poly = closest_poly.drop(right_df.geometry.name, axis=1)
        closest_poly = closest_poly.reset_index(drop=True)

        # Join values
        join = geom.join(closest_poly, lsuffix='_%s' % lsuffix, rsuffix='_%s' % rsuffix)

        # Add information about distance to closest geometry if requested
        if report_dist:
            if 'dist' in join.columns:
                raise ValueError("'dist' column exists in the DataFrame. Remove it, or set 'report_dist' to False.")
            join['dist'] = distance

        closest_geometries = closest_geometries.append(join, ignore_index=True, sort=False)

    # Merge everything together
    result = pip_join.append(closest_geometries, ignore_index=True, sort=False)
    return result

In [59]:
print(f"[!] Start Loading: {datetime.now()}")
nearest_join = sjoin_nearest(left_df=gdf_problem, right_df=nodes_proj, report_dist=True)
print(f"[!] End Loading: {datetime.now()}")
nearest_join.head()


[!] Start Loading: 2021-01-10 21:54:32.570852
Incorrect input geometry type. Skipping ..


UnboundLocalError: local variable 'closest_poly' referenced before assignment

In [60]:
import geopandas as gpd
from shapely.ops import nearest_points
from shapely.geometry import Point
from geopandas import sjoin as sjoin_old


class GeoDataFrame2(gpd.GeoDataFrame):
    
    def distances(self, other, poly_distance="min"):
        """
        Compute distance from geometry in self to all geometries in other.
        """
        if poly_distance == "min":
            # find nearest points in polygons
            nearest = [[nearest_points(in_o, in_s) for _, in_o in other.geometry.items()] for _, in_s in self.geometry.items()]
            # compute distances
            d = [[p1.distance(p2) for p1, p2 in sub] for sub in nearest]
        elif poly_distance == "centroid":
            # compute distances directly from centroids
            d = [[in_o.centroid.distance(in_s.centroid) for _, in_o in other.geometry.items()] for _, in_s in self.geometry.items()]
        else:
            raise ValueError('poly_distance must be one of "min" or "centroid"')
        return self.__class__(data=d, index=self.index.array, columns=other.index.array)
    
    
    def distance(self, other_geometry, poly_distance="min"):
        """
        Compute distance from geometry in self to single point.
        """
        other_is_point = isinstance(other_geometry, Point)
        all_in_self_points = all((isinstance(el, Point) for el in self.geometry))
        if all_in_self_points and (other_is_point or all(isinstance(el, Point) for el in other_geometry.geometry)):
            # all points, use existing distance method
            return super().distance(other_geometry)
        else:
            d = [other_geometry] * self.shape[0]
            other = self.__class__(d, columns=["geometry"], geometry="geometry")
            return self.distances(other=other, poly_distance=poly_distance)


def sjoin(left_df, right_df, how='inner', op='intersects', lsuffix='left', rsuffix='right', report_dist=False):

    # rederict to existing sjoin when possible
    if op != "near":
        return sjoin_old(left_df, right_df, how='inner', op='intersects', lsuffix='left', rsuffix='right')
    
    # manipulate DataFrames to accomodate 'how' parameter
    if how=="inner":
        # this isn't working, using .loc makes the GeoDataFrame a regular DataFrame (?)
        intersection = left_df.index.intersection(right_df.index)
        left_df = left_df.loc[intersection]
        right_df = right_df.loc[intersection]
    elif how=="right":
        left_df, right_df = right_df, left_df

    # find all distances
    d = left_df.distances(other=right_df)
    
    # find index in right dataframe corresponding to the min distance
    nearest_ind_in_right = d.idxmin(axis=1).to_list()
    
    # create a DF indexed as left_df that has info one the closest geometry in right_df
    right_items = right_df.drop(right_df.geometry.name, axis=1).loc[nearest_ind_in_right]
    right_items["index_right"] = nearest_ind_in_right
    right_items.index = left_df.index
    
    # add distances if requested
    if report_dist:
        right_items["dist"] = d.min(axis=1)

    return left_df.join(right_items, lsuffix=f'_{lsuffix}', rsuffix=f'_{rsuffix}')

In [61]:
gdf_prob_2 = GeoDataFrame2(gdf_problem)
gdf_prob_2.head()

latitude  longitude  accidents  total_injured  total_killed  \
3   40.503414 -74.244960          1            0.0           0.0   
5   40.504482 -74.247270          1            2.0           0.0   
10  40.507458 -74.235855          1            0.0           0.0   
12  40.507880 -74.229240          1            0.0           0.0   
17  40.509180 -74.247040          1            0.0           0.0   

                      geometry  
3   POINT (-74.24496 40.50341)  
5   POINT (-74.24727 40.50448)  
10  POINT (-74.23586 40.50746)  
12  POINT (-74.22924 40.50788)  
17  POINT (-74.24704 40.50918)

In [64]:
nearest_join = sjoin(left_df=gdf_prob_2, right_df=edges_proj, report_dist=True, op="near", how="left")

KeyboardInterrupt: 

In [63]:
nearest_join

latitude  longitude  accidents  total_injured  total_killed  \
3   40.503414 -74.244960          1            0.0           0.0   
5   40.504482 -74.247270          1            2.0           0.0   
10  40.507458 -74.235855          1            0.0           0.0   
12  40.507880 -74.229240          1            0.0           0.0   
17  40.509180 -74.247040          1            0.0           0.0   
19  40.509666 -74.218070          1            2.0           0.0   
21  40.510080 -74.250760          1            0.0           0.0   
22  40.510117 -74.249200          1            0.0           0.0   
25  40.511127 -74.248886          1            0.0           0.0   
26  40.511147 -74.241290          1            0.0           0.0   
28  40.511670 -74.249410          1            0.0           0.0   
32  40.512028 -74.249760          3            0.0           0.0   
33  40.512060 -74.250824          1            0.0           0.0   
35  40.512470 -74.236984          1            0.0           0.0   
38  40.513320 -74.244390          1            0.0           0.0   
39  40.513325 -74.248085          1            0.0           0.0   
40  40.513470 -74.248890          1            0.0           0.0   
41  40.513480 -74.247760          1            0.0           0.0   
43  40.514103 -74.243256          1            0.0           0.0   
49  40.514534 -74.211520          1            2.0           0.0   
53  40.514957 -74.245390          1            0.0           0.0   
59  40.516457 -74.196884          1            0.0           0.0   
60  40.516594 -74.237660          1            0.0           0.0   
62  40.516804 -74.233480          1            2.0           0.0   
64  40.516956 -74.233690          1            0.0           0.0   
65  40.517100 -74.233894          7            0.0           0.0   
68  40.518000 -74.212620          1            0.0           0.0   
69  40.518196 -74.223800          2            2.0           0.0   
71  40.518520 -74.197080          1            0.0           0.0   
72  40.519054 -74.229800          1            0.0           0.0   
75  40.520092 -74.188160          1            0.0           0.0   
76  40.520283 -74.196470          1            0.0           0.0   
78  40.521038 -74.236565          1            0.0           0.0   
79  40.521140 -74.217240          3            0.0           0.0   
81  40.521835 -74.235040          1            0.0           0.0   
83  40.521935 -74.216900          1            0.0           0.0   
85  40.522522 -74.209660          1            0.0           0.0   
87  40.522808 -74.234924          1            2.0           0.0   
89  40.523464 -74.234856          1            0.0           0.0   
91  40.523624 -74.199554          1            0.0           0.0   
92  40.523884 -74.239204          1            2.0           0.0   

                      geometry          y          x  ref          highway  \
3   POINT (-74.24496 40.50341)  40.504116 -74.245201  NaN              NaN   
5   POINT (-74.24727 40.50448)  40.503757 -74.247023  NaN              NaN   
10  POINT (-74.23586 40.50746)  40.507548 -74.235348  NaN              NaN   
12  POINT (-74.22924 40.50788)  40.507754 -74.230063  NaN  traffic_signals   
17  POINT (-74.24704 40.50918)  40.509045 -74.246903  NaN  traffic_signals   
19  POINT (-74.21807 40.50967)  40.508600 -74.223777  NaN              NaN   
21  POINT (-74.25076 40.51008)  40.509580 -74.250260  NaN              NaN   
22  POINT (-74.24920 40.51012)  40.510052 -74.249357  NaN              NaN   
25  POINT (-74.24889 40.51113)  40.510781 -74.249138  NaN              NaN   
26  POINT (-74.24129 40.51115)  40.511752 -74.241589  NaN              NaN   
28  POINT (-74.24941 40.51167)  40.512351 -74.250041  NaN              NaN   
32  POINT (-74.24976 40.51203)  40.512351 -74.250041  NaN              NaN   
33  POINT (-74.25082 40.51206)  40.511879 -74.251148  NaN              NaN   
35  POINT (-74.23698 40.51247)  40.512122 -74.236865  Na

## Next attempt

In [76]:
(f"({row.lat},{row.long})") for row in gdf_problem["latitude","longitude"].itterrows()

SyntaxError: invalid syntax (<ipython-input-76-abd6a24fc738>, line 1)

In [98]:
query = [f"{row[1].latitude}, {row[1].longitude}"  for row in gdf_problem[["latitude","longitude"]].iterrows()]

In [100]:

ox.geocode_to_gdf(query, which_result=1, by_osmid=False, buffer_dist=None)

geometry  bbox_north  bbox_south  \
0   POLYGON ((-74.24527 40.50337, -74.24524 40.503...   40.503402   40.503272   
1   POLYGON ((-74.24763 40.50430, -74.24761 40.504...   40.504413   40.504213   
2   POLYGON ((-74.23605 40.50731, -74.23601 40.507...   40.507341   40.507181   
3   POLYGON ((-74.22937 40.50823, -74.22932 40.508...   40.508239   40.508059   
4   POLYGON ((-74.24742 40.50912, -74.24736 40.509...   40.509214   40.509050   
5   LINESTRING (-74.21802 40.50967, -74.21861 40.5...   40.509670   40.509552   
6   POLYGON ((-74.25105 40.51006, -74.25102 40.510...   40.510094   40.509932   
7   POLYGON ((-74.24943 40.51032, -74.24931 40.510...   40.510349   40.510210   
8   POLYGON ((-74.24882 40.51121, -74.24873 40.511...   40.511429   40.511109   
9   POLYGON ((-74.24144 40.51097, -74.24138 40.510...   40.511035   40.510796   
10  POLYGON ((-74.24961 40.51153, -74.24958 40.511...   40.511615   40.511469   
11  POLYGON ((-74.24975 40.51216, -74.24970 40.512...   40.512259   40.512114   
12  POLYGON ((-74.25094 40.51220, -74.25086 40.512...   40.512225   40.512112   
13  POLYGON ((-74.23688 40.51261, -74.23685 40.512...   40.512653   40.512552   
14  POLYGON ((-74.24463 40.51324, -74.24456 40.513...   40.513286   40.513167   
15  POLYGON ((-74.24819 40.51355, -74.24806 40.513...   40.513617   40.513414   
16                         POINT (-74.24880 40.51356)   40.513615   40.513514   
17  POLYGON ((-74.24778 40.51331, -74.24768 40.513...   40.513366   40.513204   
18  POLYGON ((-74.24317 40.51419, -74.24313 40.514...   40.514270   40.514147   
19  POLYGON ((-74.21226 40.51441, -74.21224 40.514...   40.514597   40.514125   
20  POLYGON ((-74.24534 40.51480, -74.24525 40.514...   40.514844   40.514716   
21  POLYGON ((-74.19799 40.51733, -74.19794 40.516...   40.518071   40.516026   
22  POLYGON ((-74.23782 40.51680, -74.23772 40.516...   40.516838   40.516694   
23  POLYGON ((-74.23343 40.51696, -74.23328 40.516...   40.517067   40.516872   
24  POLYGON ((-74.23374 40.51731, -74.23357 40.517...   40.517365   40.517097   
25  POLYGON ((-74.23402 40.51752, -74.23390 40.517...   40.517575   40.517340   
26  POLYGON ((-74.21249 40.51813, -74.21247 40.518...   40.518231   40.518081   
27  POLYGON ((-74.22409 40.51828, -74.22402 40.518...   40.518415   40.518275   
28  POLYGON ((-74.19736 40.51846, -74.19735 40.518...   40.518480   40.518424   
29  POLYGON ((-74.22981 40.51930, -74.22977 40.519...   40.519389   40.519156   
30  POLYGON ((-74.18819 40.52039, -74.18816 40.520...   40.520462   40.520339   
31  POLYGON ((-74.19676 40.52020, -74.19673 40.520...   40.520284   40.520164   
32  POLYGON ((-74.23752 40.52021, -74.23716 40.520...   40.520843   40.520190   
33  POLYGON ((-74.21771 40.52102, -74.21769 40.520...   40.521152   40.520911   
34  POLYGON ((-74.23472 40.52167, -74.23452 40.521...   40.521808   40.521658   
35  POLYGON ((-74.21737 40.52207, -74.21735 40.521...   40.522122   40.521957   
36  POLYGON ((-74.21001 40.52259, -74.20991 40.522...   40.522717   40.522547   
37  POLYGON ((-74.23464 40.52236, -74.23445 40.522...   40.522631   40.522345   
38  POLYGON ((-74.23455 40.52318, -74.23436 40.523...   40.523452   40.523168   
39                         POINT (-74.19958 40.52376)   40.523806   40.523706   
40                         POINT (-74.23929 40.52388)   40.523927   40.523827   

    bbox_east  bbox_west   place_id osm_type      osm_id        lat  \
0  -74.245099 -74.245275  148488164      way   241855666  40.503337   
1  -74.247411 -74.247630  148567172      way   241858446  40.504345   
2  -74.235805 -74.236055  152163693      way   246727725  40.507282   
3  -74.229251 -74.229368  150854497      way   245140720  40.508159   
4  -74.247067 -74.247422  152349656      way   245138913  40.509133   
5  -74.218023 -74.218611  186781937      way   420303028  40.509670   
6  -74.250849 -74.251053  149300022      way   245138616  40.510002   
7  -74.249267 -74.249425  151421334      way   245139102  40.510279   
8  

### Other one

In [155]:
print(f"[!] Start Loading: {datetime.now()}")
print(ox.get_nearest_edges(G, gdf_problem.longitude.to_list(), gdf_problem.latitude.to_list(), method='kdtree'))
print(f"[!] End Loading: {datetime.now()}")
            

[!] Start Loading: 2021-01-11 01:23:00.532970
[[  42989156   42991087          0]
 [  42951353   42989162          0]
 [  43007069   43007072          0]
 [  42976153   42989117          0]
 [  42960083   42991645          0]
 [  42984493   42985081          0]
 [  42978564   42976280          0]
 [  42978557   42978560          0]
 [  43003516 3148398080          0]
 [  42975904   42991591          0]
 [  43003516 3148398080          0]
 [  43003516 3148398080          0]
 [  42979946   43003569          0]
 [  43013796   42991575          0]
 [  42975898   42975901          0]
 [  42950784   42994933          0]
 [  42976583   42994933          0]
 [  42994933   42950784          0]
 [  42978540   42962429          0]
 [  42984482   42984493          0]
 [  42994069   42975898          0]
 [  43002970   42959957          0]
 [  42953163   42959848          0]
 [  42991570   43000925          0]
 [  43000925   42991570          0]
 [  42991570   43000925          0]
 [  42984466   429